name:                aoc2022
version:             1.0.0.0
github:              "StephenSwat/aoc2022-hs"
license:             Unlicense
author:              "Stephen Nicholas Swatman"
maintainer:          "stephen@v25.nl"

dependencies:
  - base >= 4.16 && < 5
  - split
  - containers
  - extra
  - parsec
  - mtl
  - pretty-show
  - ilist
  - lens

executables:
  aoc2022:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
      - -Wall
      - -Wcompat
      - -O3
